disabled_rules:
    - identifier_name
    - trailing_whitespace
    - cyclomatic_complexity
    - multiple_closures_with_trailing_closure
    - unused_closure_parameter

excluded:
  - Pods
  
type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 100
  error: 200
  
line_length:
  warning: 300
  error: 500

ignores_function_declarations: true
ignores_comments: true
ignores_urls: true
