disabled_rules:
    - identifier_name
    - multiple_closures_with_trailing_closure
    - trailing_whitespace
    - shorthand_operator
    - force_try
    - trailing_comma
    - type_name
    - cyclomatic_complexity
    - large_tuple
    - force_cast

excluded:
  - Pods

function_body_length:
  warning: 100
  error: 200
  
line_length:
  warning: 300
  error: 500
